---
abstract: 'AjiFry Language (アジフライ語) Translator'
author:
  - 'moznion  C<< <moznion[at]gmail.com> >>'
build_requires:
  File::Compare: 1.1005
  File::Copy: 2.13
  File::Spec::Functions: 0
  FindBin: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.4003
dynamic_config: 0
generated_by: 'Minilla/v0.4.4, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-AjiFry
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Acme::AjiFry:
    file: lib/Acme/AjiFry.pm
    version: 0.09
  Acme::AjiFry::EN:
    file: lib/Acme/AjiFry/EN.pm
  Acme::AjiFry::Perl:
    file: lib/Acme/AjiFry/Perl.pm
requires:
  Encode: 2.39
  Filter::Simple: 0.84
  List::Util: 1.22
  perl: 5.008009
resources:
  bugtracker: https://github.com/moznion/Acme--AjiFry/issues
  homepage: https://github.com/moznion/Acme--AjiFry
  repository: git://github.com/moznion/Acme--AjiFry.git
version: 0.09
x_contributors:
  - 'papix <papix2011@gmail.com>'
  - 'papix <mail@papix.net>'
  - 'moznion <moznion@gmail.com>'
