---
abstract: 'AjiFry Language (アジフライ語) Translator'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  Cwd: 0
  Encode: 2.39
  File::Basename: 2.78
  File::Compare: 1.1006
  File::Copy: 2.18
  Test::More: 0.98
configure_requires:
  Module::Build: 0.40
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-AjiFry
no_index:
  directory:
    - inc
provides:
  Acme::AjiFry:
    file: lib/Acme/AjiFry.pm
    version: 0.08
  Acme::AjiFry::EN:
    file: lib/Acme/AjiFry/EN.pm
    version: 0
  Acme::AjiFry::Perl:
    file: lib/Acme/AjiFry/Perl.pm
    version: 0
requires:
  Carp: 0
  Class::Accessor::Fast: 0.34
  Filter::Simple: 0.84
  List::Util: 1.22
  base: 0
  perl: 5.010000
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/moznion/Acme--AjiFry.git
version: 0.08
