---
abstract: 'AjiFry Language (アジフライ語) Translator'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.63
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.63
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-AjiFry
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor::Fast: 0.34
  perl: 5.010000
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/moznion/Acme--AjiFry.git
version: 0.05
